org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

# Version de Forge para Minecraft 1.21.1 (el workflow de GitHub la reemplaza por la ultima disponible)
mc_version=1.21.1
forge_version=52.1.0
