modLoader="javafml"
loaderVersion="[52,)"
license="All Rights Reserved"

[[mods]]
modId="ludokressh"
version="1.0.0"
displayName="Ludo Kressh Sword"
authors="Ricardo"
description='''La espada de Ludo Kressh, con el mismo modelo 3D y las mismas stats que el mod de Skyrim.
Cada golpe aplica el Veneno Sith.'''

[[dependencies.ludokressh]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ludokressh]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
