plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
}

version = mod_version
group = 'com.ricardo.orangesaiyan'

base {
    archivesName = 'orangesaiyan'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            property 'geckolib.disable_examples', 'true'
            mods {
                orangesaiyan {
                    source sourceSets.main
                }
            }
        }
        client {}
        server {
            args '--nogui'
        }
    }
}

repositories {
    maven {
        name = 'GeckoLib'
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex 'software\\.bernie.*'
            includeGroup 'com.eliotlash.mclib'
        }
    }
    flatDir {
        dirs 'libs'
    }
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    compileOnly fg.deobf("local:dragonminez:${dragonminez_version}")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : 'orangesaiyan',
                'Specification-Vendor'    : 'Ricardo',
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.version,
                'Implementation-Vendor'   : 'Ricardo'
        ])
    }
    finalizedBy 'reobfJar'
}
